name: cmweather-docs
channels:
  - conda-forge
dependencies:
  - numpydoc
  - pydata-sphinx-theme
  - nbsphinx
  - ipython
  - ipykernel
  - netcdf4
  - xarray
  - pooch
  - myst-nb
  - myst-parser
  - sphinx-design
  - pip
  - pip:
      - sphinxext-opengraph
      - -e ..
